version: "3.8"
services:
  db:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_NAME
    ports:
      - "$DB_PORT:5432"
    volumes:
      - "data:/var/lib/postgresql/data"

volumes:
  data:
