# Generated by Django 3.2.6 on 2021-08-16 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Single chioce', 'Single'), ('Miltiple choice', 'Multiple')], max_length=15, verbose_name='The type of the question')),
                ('content', models.TextField(help_text='The question text')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the question was created')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the question was last updated')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Question answer')),
                ('is_correct', models.BooleanField(default=False, help_text='True if answer correct to the question')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the question was created')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the question was last updated')),
                ('question', models.ForeignKey(help_text='The question that answer is to', on_delete=django.db.models.deletion.PROTECT, to='quizapp.question')),
            ],
        ),
    ]
